# Generated by Django 3.2.7 on 2021-09-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Слово')),
                ('topic', models.CharField(choices=[('PL', 'Растения'), ('AN', 'Животные'), ('TW', 'Города'), ('NM', 'Имена'), ('RM', 'Случайные')], max_length=2, verbose_name='Тема')),
            ],
        ),
    ]
