# Generated by Django 3.2.7 on 2021-09-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='first',
            field=models.CharField(blank=True, max_length=1, verbose_name='Первая буква'),
        ),
        migrations.AddField(
            model_name='word',
            name='last',
            field=models.CharField(blank=True, max_length=1, verbose_name='Последняя буква'),
        ),
        migrations.AlterField(
            model_name='word',
            name='topic',
            field=models.CharField(choices=[('PL', 'Растения'), ('AN', 'Животные'), ('TW', 'Города'), ('NM', 'Имена')], max_length=2, verbose_name='Тема'),
        ),
    ]
